trail project for microverse
jossi30/trail-project pull request #1
Opened 2022-12-06 21:00 UTC by jossi30

2022-12-06 21:19 UTC, jossi30 commented on index.html
> +
good job on using h1 for the header , however, try to use more classes instead of using id for every element.

2022-12-06 21:19 UTC, jossi30 commented on index.html
> +</div>
great job so far, but it is advisable to add an alt to the image for accessibility purposes.

2022-12-06 21:19 UTC, jossi30 commented on style.css
> +    padding-top: 3%;
you are doing great so far, I really like the design but try using flexbox on the container to place elements on the page for more dynamic styling.

2022-12-06 21:19 UTC, jossi30 commented on index.html
> +      <p id="tagline">Coding partner in microverse!</p>
nice job creating a header section but try to use the header tag instead of the main for semantic purposes.

2022-12-06 21:19 UTC, jossi30 commented on index.html
> +    Antalya, TURKEY</li><br>
good job so far, however, try to use the tag section to contain the list for semantic purposes.

2022-12-06 22:56 UTC, Owusu-Desmond commented on index.html
> +</div>
- [ ] Hi @jossi30, Good to use inline comments :+1: but please make sure your comments are politely stated as suggestions instead of orders :relaxed: . For example:

*"I think it would be better to give your image tags the `alt` attribute to make the image accessible to disabled users"*

2022-12-06 23:05 UTC, Owusu-Desmond requested changes
Hi @jossi30  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 

:heavy_check_mark: Good to use emojis to make your review user friendly
:heavy_check_mark: Good to use inline comments


 ## Required Changes ♻️
_Check the comments under your review._

- [ ] Please make sure that you submit a review with a review summary in the Pull Request the student opened utilizing the "Review changes" :pray: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 20:00 UTC, binhussen approved these changes
Hi @jossi30 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions
- [Optionnal] kindly be polite when you review ❤️

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 20:19 UTC, merged